### ISSUE TITLE
Wrong posts url

### ISSUE THREAD

**Issue by Stopy** [yanislav-igonin/dumpach#1]
![dumpach - google chrome](https://user-images.githubusercontent.com/8018771/31050283-68eb442a-a64e-11e7-8af4-03ce4a289e01.jpg)

**Comment by yanislav-igonin** [comment]
@Stopy на чем серфишь, братишка?
на хроме все в поряде
![screenshot from 2017-10-02 12-35-47](https://user-images.githubusercontent.com/15846431/31072009-e9f14530-a76e-11e7-9916-8fc3a6f3a3ec.png)
